# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-5.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-5.app/Contents/bin/cmake" -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-5.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gewaltig/Code/sli3/tight-storage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gewaltig/Code/sli3/tight-storage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-5.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-5.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gewaltig/Code/sli3/tight-storage/CMakeFiles /Users/gewaltig/Code/sli3/tight-storage/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gewaltig/Code/sli3/tight-storage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sli3

# Build rule for target.
sli3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sli3
.PHONY : sli3

# fast build rule for target.
sli3/fast:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/build
.PHONY : sli3/fast

sli_allocator.o: sli_allocator.cpp.o
.PHONY : sli_allocator.o

# target to build an object file
sli_allocator.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_allocator.cpp.o
.PHONY : sli_allocator.cpp.o

sli_allocator.i: sli_allocator.cpp.i
.PHONY : sli_allocator.i

# target to preprocess a source file
sli_allocator.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_allocator.cpp.i
.PHONY : sli_allocator.cpp.i

sli_allocator.s: sli_allocator.cpp.s
.PHONY : sli_allocator.s

# target to generate assembly for a file
sli_allocator.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_allocator.cpp.s
.PHONY : sli_allocator.cpp.s

sli_array.o: sli_array.cpp.o
.PHONY : sli_array.o

# target to build an object file
sli_array.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_array.cpp.o
.PHONY : sli_array.cpp.o

sli_array.i: sli_array.cpp.i
.PHONY : sli_array.i

# target to preprocess a source file
sli_array.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_array.cpp.i
.PHONY : sli_array.cpp.i

sli_array.s: sli_array.cpp.s
.PHONY : sli_array.s

# target to generate assembly for a file
sli_array.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_array.cpp.s
.PHONY : sli_array.cpp.s

sli_arraytype.o: sli_arraytype.cpp.o
.PHONY : sli_arraytype.o

# target to build an object file
sli_arraytype.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_arraytype.cpp.o
.PHONY : sli_arraytype.cpp.o

sli_arraytype.i: sli_arraytype.cpp.i
.PHONY : sli_arraytype.i

# target to preprocess a source file
sli_arraytype.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_arraytype.cpp.i
.PHONY : sli_arraytype.cpp.i

sli_arraytype.s: sli_arraytype.cpp.s
.PHONY : sli_arraytype.s

# target to generate assembly for a file
sli_arraytype.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_arraytype.cpp.s
.PHONY : sli_arraytype.cpp.s

sli_builtins.o: sli_builtins.cpp.o
.PHONY : sli_builtins.o

# target to build an object file
sli_builtins.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_builtins.cpp.o
.PHONY : sli_builtins.cpp.o

sli_builtins.i: sli_builtins.cpp.i
.PHONY : sli_builtins.i

# target to preprocess a source file
sli_builtins.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_builtins.cpp.i
.PHONY : sli_builtins.cpp.i

sli_builtins.s: sli_builtins.cpp.s
.PHONY : sli_builtins.s

# target to generate assembly for a file
sli_builtins.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_builtins.cpp.s
.PHONY : sli_builtins.cpp.s

sli_charcode.o: sli_charcode.cpp.o
.PHONY : sli_charcode.o

# target to build an object file
sli_charcode.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_charcode.cpp.o
.PHONY : sli_charcode.cpp.o

sli_charcode.i: sli_charcode.cpp.i
.PHONY : sli_charcode.i

# target to preprocess a source file
sli_charcode.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_charcode.cpp.i
.PHONY : sli_charcode.cpp.i

sli_charcode.s: sli_charcode.cpp.s
.PHONY : sli_charcode.s

# target to generate assembly for a file
sli_charcode.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_charcode.cpp.s
.PHONY : sli_charcode.cpp.s

sli_control.o: sli_control.cpp.o
.PHONY : sli_control.o

# target to build an object file
sli_control.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_control.cpp.o
.PHONY : sli_control.cpp.o

sli_control.i: sli_control.cpp.i
.PHONY : sli_control.i

# target to preprocess a source file
sli_control.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_control.cpp.i
.PHONY : sli_control.cpp.i

sli_control.s: sli_control.cpp.s
.PHONY : sli_control.s

# target to generate assembly for a file
sli_control.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_control.cpp.s
.PHONY : sli_control.cpp.s

sli_dictionary.o: sli_dictionary.cpp.o
.PHONY : sli_dictionary.o

# target to build an object file
sli_dictionary.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_dictionary.cpp.o
.PHONY : sli_dictionary.cpp.o

sli_dictionary.i: sli_dictionary.cpp.i
.PHONY : sli_dictionary.i

# target to preprocess a source file
sli_dictionary.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_dictionary.cpp.i
.PHONY : sli_dictionary.cpp.i

sli_dictionary.s: sli_dictionary.cpp.s
.PHONY : sli_dictionary.s

# target to generate assembly for a file
sli_dictionary.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_dictionary.cpp.s
.PHONY : sli_dictionary.cpp.s

sli_dictstack.o: sli_dictstack.cpp.o
.PHONY : sli_dictstack.o

# target to build an object file
sli_dictstack.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_dictstack.cpp.o
.PHONY : sli_dictstack.cpp.o

sli_dictstack.i: sli_dictstack.cpp.i
.PHONY : sli_dictstack.i

# target to preprocess a source file
sli_dictstack.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_dictstack.cpp.i
.PHONY : sli_dictstack.cpp.i

sli_dictstack.s: sli_dictstack.cpp.s
.PHONY : sli_dictstack.s

# target to generate assembly for a file
sli_dictstack.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_dictstack.cpp.s
.PHONY : sli_dictstack.cpp.s

sli_dicttype.o: sli_dicttype.cpp.o
.PHONY : sli_dicttype.o

# target to build an object file
sli_dicttype.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_dicttype.cpp.o
.PHONY : sli_dicttype.cpp.o

sli_dicttype.i: sli_dicttype.cpp.i
.PHONY : sli_dicttype.i

# target to preprocess a source file
sli_dicttype.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_dicttype.cpp.i
.PHONY : sli_dicttype.cpp.i

sli_dicttype.s: sli_dicttype.cpp.s
.PHONY : sli_dicttype.s

# target to generate assembly for a file
sli_dicttype.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_dicttype.cpp.s
.PHONY : sli_dicttype.cpp.s

sli_exceptions.o: sli_exceptions.cpp.o
.PHONY : sli_exceptions.o

# target to build an object file
sli_exceptions.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_exceptions.cpp.o
.PHONY : sli_exceptions.cpp.o

sli_exceptions.i: sli_exceptions.cpp.i
.PHONY : sli_exceptions.i

# target to preprocess a source file
sli_exceptions.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_exceptions.cpp.i
.PHONY : sli_exceptions.cpp.i

sli_exceptions.s: sli_exceptions.cpp.s
.PHONY : sli_exceptions.s

# target to generate assembly for a file
sli_exceptions.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_exceptions.cpp.s
.PHONY : sli_exceptions.cpp.s

sli_functiontype.o: sli_functiontype.cpp.o
.PHONY : sli_functiontype.o

# target to build an object file
sli_functiontype.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_functiontype.cpp.o
.PHONY : sli_functiontype.cpp.o

sli_functiontype.i: sli_functiontype.cpp.i
.PHONY : sli_functiontype.i

# target to preprocess a source file
sli_functiontype.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_functiontype.cpp.i
.PHONY : sli_functiontype.cpp.i

sli_functiontype.s: sli_functiontype.cpp.s
.PHONY : sli_functiontype.s

# target to generate assembly for a file
sli_functiontype.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_functiontype.cpp.s
.PHONY : sli_functiontype.cpp.s

sli_integertype.o: sli_integertype.cpp.o
.PHONY : sli_integertype.o

# target to build an object file
sli_integertype.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_integertype.cpp.o
.PHONY : sli_integertype.cpp.o

sli_integertype.i: sli_integertype.cpp.i
.PHONY : sli_integertype.i

# target to preprocess a source file
sli_integertype.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_integertype.cpp.i
.PHONY : sli_integertype.cpp.i

sli_integertype.s: sli_integertype.cpp.s
.PHONY : sli_integertype.s

# target to generate assembly for a file
sli_integertype.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_integertype.cpp.s
.PHONY : sli_integertype.cpp.s

sli_interpreter.o: sli_interpreter.cpp.o
.PHONY : sli_interpreter.o

# target to build an object file
sli_interpreter.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_interpreter.cpp.o
.PHONY : sli_interpreter.cpp.o

sli_interpreter.i: sli_interpreter.cpp.i
.PHONY : sli_interpreter.i

# target to preprocess a source file
sli_interpreter.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_interpreter.cpp.i
.PHONY : sli_interpreter.cpp.i

sli_interpreter.s: sli_interpreter.cpp.s
.PHONY : sli_interpreter.s

# target to generate assembly for a file
sli_interpreter.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_interpreter.cpp.s
.PHONY : sli_interpreter.cpp.s

sli_iostreamtype.o: sli_iostreamtype.cpp.o
.PHONY : sli_iostreamtype.o

# target to build an object file
sli_iostreamtype.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_iostreamtype.cpp.o
.PHONY : sli_iostreamtype.cpp.o

sli_iostreamtype.i: sli_iostreamtype.cpp.i
.PHONY : sli_iostreamtype.i

# target to preprocess a source file
sli_iostreamtype.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_iostreamtype.cpp.i
.PHONY : sli_iostreamtype.cpp.i

sli_iostreamtype.s: sli_iostreamtype.cpp.s
.PHONY : sli_iostreamtype.s

# target to generate assembly for a file
sli_iostreamtype.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_iostreamtype.cpp.s
.PHONY : sli_iostreamtype.cpp.s

sli_main.o: sli_main.cpp.o
.PHONY : sli_main.o

# target to build an object file
sli_main.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_main.cpp.o
.PHONY : sli_main.cpp.o

sli_main.i: sli_main.cpp.i
.PHONY : sli_main.i

# target to preprocess a source file
sli_main.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_main.cpp.i
.PHONY : sli_main.cpp.i

sli_main.s: sli_main.cpp.s
.PHONY : sli_main.s

# target to generate assembly for a file
sli_main.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_main.cpp.s
.PHONY : sli_main.cpp.s

sli_math.o: sli_math.cpp.o
.PHONY : sli_math.o

# target to build an object file
sli_math.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_math.cpp.o
.PHONY : sli_math.cpp.o

sli_math.i: sli_math.cpp.i
.PHONY : sli_math.i

# target to preprocess a source file
sli_math.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_math.cpp.i
.PHONY : sli_math.cpp.i

sli_math.s: sli_math.cpp.s
.PHONY : sli_math.s

# target to generate assembly for a file
sli_math.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_math.cpp.s
.PHONY : sli_math.cpp.s

sli_name.o: sli_name.cpp.o
.PHONY : sli_name.o

# target to build an object file
sli_name.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_name.cpp.o
.PHONY : sli_name.cpp.o

sli_name.i: sli_name.cpp.i
.PHONY : sli_name.i

# target to preprocess a source file
sli_name.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_name.cpp.i
.PHONY : sli_name.cpp.i

sli_name.s: sli_name.cpp.s
.PHONY : sli_name.s

# target to generate assembly for a file
sli_name.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_name.cpp.s
.PHONY : sli_name.cpp.s

sli_nametype.o: sli_nametype.cpp.o
.PHONY : sli_nametype.o

# target to build an object file
sli_nametype.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_nametype.cpp.o
.PHONY : sli_nametype.cpp.o

sli_nametype.i: sli_nametype.cpp.i
.PHONY : sli_nametype.i

# target to preprocess a source file
sli_nametype.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_nametype.cpp.i
.PHONY : sli_nametype.cpp.i

sli_nametype.s: sli_nametype.cpp.s
.PHONY : sli_nametype.s

# target to generate assembly for a file
sli_nametype.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_nametype.cpp.s
.PHONY : sli_nametype.cpp.s

sli_numerics.o: sli_numerics.cpp.o
.PHONY : sli_numerics.o

# target to build an object file
sli_numerics.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_numerics.cpp.o
.PHONY : sli_numerics.cpp.o

sli_numerics.i: sli_numerics.cpp.i
.PHONY : sli_numerics.i

# target to preprocess a source file
sli_numerics.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_numerics.cpp.i
.PHONY : sli_numerics.cpp.i

sli_numerics.s: sli_numerics.cpp.s
.PHONY : sli_numerics.s

# target to generate assembly for a file
sli_numerics.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_numerics.cpp.s
.PHONY : sli_numerics.cpp.s

sli_parser.o: sli_parser.cpp.o
.PHONY : sli_parser.o

# target to build an object file
sli_parser.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_parser.cpp.o
.PHONY : sli_parser.cpp.o

sli_parser.i: sli_parser.cpp.i
.PHONY : sli_parser.i

# target to preprocess a source file
sli_parser.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_parser.cpp.i
.PHONY : sli_parser.cpp.i

sli_parser.s: sli_parser.cpp.s
.PHONY : sli_parser.s

# target to generate assembly for a file
sli_parser.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_parser.cpp.s
.PHONY : sli_parser.cpp.s

sli_scanner.o: sli_scanner.cpp.o
.PHONY : sli_scanner.o

# target to build an object file
sli_scanner.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_scanner.cpp.o
.PHONY : sli_scanner.cpp.o

sli_scanner.i: sli_scanner.cpp.i
.PHONY : sli_scanner.i

# target to preprocess a source file
sli_scanner.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_scanner.cpp.i
.PHONY : sli_scanner.cpp.i

sli_scanner.s: sli_scanner.cpp.s
.PHONY : sli_scanner.s

# target to generate assembly for a file
sli_scanner.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_scanner.cpp.s
.PHONY : sli_scanner.cpp.s

sli_stack.o: sli_stack.cpp.o
.PHONY : sli_stack.o

# target to build an object file
sli_stack.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_stack.cpp.o
.PHONY : sli_stack.cpp.o

sli_stack.i: sli_stack.cpp.i
.PHONY : sli_stack.i

# target to preprocess a source file
sli_stack.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_stack.cpp.i
.PHONY : sli_stack.cpp.i

sli_stack.s: sli_stack.cpp.s
.PHONY : sli_stack.s

# target to generate assembly for a file
sli_stack.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_stack.cpp.s
.PHONY : sli_stack.cpp.s

sli_stringtype.o: sli_stringtype.cpp.o
.PHONY : sli_stringtype.o

# target to build an object file
sli_stringtype.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_stringtype.cpp.o
.PHONY : sli_stringtype.cpp.o

sli_stringtype.i: sli_stringtype.cpp.i
.PHONY : sli_stringtype.i

# target to preprocess a source file
sli_stringtype.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_stringtype.cpp.i
.PHONY : sli_stringtype.cpp.i

sli_stringtype.s: sli_stringtype.cpp.s
.PHONY : sli_stringtype.s

# target to generate assembly for a file
sli_stringtype.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_stringtype.cpp.s
.PHONY : sli_stringtype.cpp.s

sli_token.o: sli_token.cpp.o
.PHONY : sli_token.o

# target to build an object file
sli_token.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_token.cpp.o
.PHONY : sli_token.cpp.o

sli_token.i: sli_token.cpp.i
.PHONY : sli_token.i

# target to preprocess a source file
sli_token.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_token.cpp.i
.PHONY : sli_token.cpp.i

sli_token.s: sli_token.cpp.s
.PHONY : sli_token.s

# target to generate assembly for a file
sli_token.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_token.cpp.s
.PHONY : sli_token.cpp.s

sli_tokenstack.o: sli_tokenstack.cpp.o
.PHONY : sli_tokenstack.o

# target to build an object file
sli_tokenstack.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_tokenstack.cpp.o
.PHONY : sli_tokenstack.cpp.o

sli_tokenstack.i: sli_tokenstack.cpp.i
.PHONY : sli_tokenstack.i

# target to preprocess a source file
sli_tokenstack.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_tokenstack.cpp.i
.PHONY : sli_tokenstack.cpp.i

sli_tokenstack.s: sli_tokenstack.cpp.s
.PHONY : sli_tokenstack.s

# target to generate assembly for a file
sli_tokenstack.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_tokenstack.cpp.s
.PHONY : sli_tokenstack.cpp.s

sli_type.o: sli_type.cpp.o
.PHONY : sli_type.o

# target to build an object file
sli_type.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_type.cpp.o
.PHONY : sli_type.cpp.o

sli_type.i: sli_type.cpp.i
.PHONY : sli_type.i

# target to preprocess a source file
sli_type.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_type.cpp.i
.PHONY : sli_type.cpp.i

sli_type.s: sli_type.cpp.s
.PHONY : sli_type.s

# target to generate assembly for a file
sli_type.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_type.cpp.s
.PHONY : sli_type.cpp.s

sli_type_trie.o: sli_type_trie.cpp.o
.PHONY : sli_type_trie.o

# target to build an object file
sli_type_trie.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_type_trie.cpp.o
.PHONY : sli_type_trie.cpp.o

sli_type_trie.i: sli_type_trie.cpp.i
.PHONY : sli_type_trie.i

# target to preprocess a source file
sli_type_trie.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_type_trie.cpp.i
.PHONY : sli_type_trie.cpp.i

sli_type_trie.s: sli_type_trie.cpp.s
.PHONY : sli_type_trie.s

# target to generate assembly for a file
sli_type_trie.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_type_trie.cpp.s
.PHONY : sli_type_trie.cpp.s

sli_typecheck.o: sli_typecheck.cpp.o
.PHONY : sli_typecheck.o

# target to build an object file
sli_typecheck.cpp.o:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_typecheck.cpp.o
.PHONY : sli_typecheck.cpp.o

sli_typecheck.i: sli_typecheck.cpp.i
.PHONY : sli_typecheck.i

# target to preprocess a source file
sli_typecheck.cpp.i:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_typecheck.cpp.i
.PHONY : sli_typecheck.cpp.i

sli_typecheck.s: sli_typecheck.cpp.s
.PHONY : sli_typecheck.s

# target to generate assembly for a file
sli_typecheck.cpp.s:
	$(MAKE) -f CMakeFiles/sli3.dir/build.make CMakeFiles/sli3.dir/sli_typecheck.cpp.s
.PHONY : sli_typecheck.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sli3"
	@echo "... sli_allocator.o"
	@echo "... sli_allocator.i"
	@echo "... sli_allocator.s"
	@echo "... sli_array.o"
	@echo "... sli_array.i"
	@echo "... sli_array.s"
	@echo "... sli_arraytype.o"
	@echo "... sli_arraytype.i"
	@echo "... sli_arraytype.s"
	@echo "... sli_builtins.o"
	@echo "... sli_builtins.i"
	@echo "... sli_builtins.s"
	@echo "... sli_charcode.o"
	@echo "... sli_charcode.i"
	@echo "... sli_charcode.s"
	@echo "... sli_control.o"
	@echo "... sli_control.i"
	@echo "... sli_control.s"
	@echo "... sli_dictionary.o"
	@echo "... sli_dictionary.i"
	@echo "... sli_dictionary.s"
	@echo "... sli_dictstack.o"
	@echo "... sli_dictstack.i"
	@echo "... sli_dictstack.s"
	@echo "... sli_dicttype.o"
	@echo "... sli_dicttype.i"
	@echo "... sli_dicttype.s"
	@echo "... sli_exceptions.o"
	@echo "... sli_exceptions.i"
	@echo "... sli_exceptions.s"
	@echo "... sli_functiontype.o"
	@echo "... sli_functiontype.i"
	@echo "... sli_functiontype.s"
	@echo "... sli_integertype.o"
	@echo "... sli_integertype.i"
	@echo "... sli_integertype.s"
	@echo "... sli_interpreter.o"
	@echo "... sli_interpreter.i"
	@echo "... sli_interpreter.s"
	@echo "... sli_iostreamtype.o"
	@echo "... sli_iostreamtype.i"
	@echo "... sli_iostreamtype.s"
	@echo "... sli_main.o"
	@echo "... sli_main.i"
	@echo "... sli_main.s"
	@echo "... sli_math.o"
	@echo "... sli_math.i"
	@echo "... sli_math.s"
	@echo "... sli_name.o"
	@echo "... sli_name.i"
	@echo "... sli_name.s"
	@echo "... sli_nametype.o"
	@echo "... sli_nametype.i"
	@echo "... sli_nametype.s"
	@echo "... sli_numerics.o"
	@echo "... sli_numerics.i"
	@echo "... sli_numerics.s"
	@echo "... sli_parser.o"
	@echo "... sli_parser.i"
	@echo "... sli_parser.s"
	@echo "... sli_scanner.o"
	@echo "... sli_scanner.i"
	@echo "... sli_scanner.s"
	@echo "... sli_stack.o"
	@echo "... sli_stack.i"
	@echo "... sli_stack.s"
	@echo "... sli_stringtype.o"
	@echo "... sli_stringtype.i"
	@echo "... sli_stringtype.s"
	@echo "... sli_token.o"
	@echo "... sli_token.i"
	@echo "... sli_token.s"
	@echo "... sli_tokenstack.o"
	@echo "... sli_tokenstack.i"
	@echo "... sli_tokenstack.s"
	@echo "... sli_type.o"
	@echo "... sli_type.i"
	@echo "... sli_type.s"
	@echo "... sli_type_trie.o"
	@echo "... sli_type_trie.i"
	@echo "... sli_type_trie.s"
	@echo "... sli_typecheck.o"
	@echo "... sli_typecheck.i"
	@echo "... sli_typecheck.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

